export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const POST_LIST_GET = "POST_LIST_GET";
export const POST_LIST_GET_SUCCESS = "POST_LIST_GET_SUCCESS";
export const POST_LIST_GET_FAILURE = "POST_LIST_GET_FAILURE";


export const POST_GET = "POST_GET";
export const POST_GET_SUCCESS = "POST_GET_SUCCESS";
export const POST_GET_FAILURE = "POST_GET_FAILURE";

export const POST_INSERT = "POST_INSERT";
export const POST_INSERT_SUCCESS = "POST_INSERT_SUCCESS";
export const POST_INSERT_FAILURE = "POST_INSERT_FAILURE";

export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";

export const POST_UPDATE = "POST_UPDATE";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";
